theme: minima
title: "Analyzing COVID-19 and Domestic Violence Incidence using Regression Discontinuity Analysis"
description: "By Elisha Clark, Kaitlyn Vana, Helen Wang, and Emily Zhao"
header_pages:
  - index.md
